"""initial empty baseline

Phase 0 baseline. Tables are added by the autogenerated Phase 1 migration,
which will have this revision as its down_revision.

Revision ID: 0001_initial_empty
Revises:
Create Date: 2026-06-23
"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0001_initial_empty"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
