"""add poll_options to generated_posts

Revision ID: 4527f99f4366
Revises: d810ad1f7031
Create Date: 2026-06-23 11:42:48.403945
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4527f99f4366'
down_revision: Union[str, None] = 'd810ad1f7031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_posts', sa.Column('poll_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key('fk_generated_posts_strategy_task', 'generated_posts', 'strategy_tasks', ['strategy_task_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_generated_posts_strategy_task', 'generated_posts', type_='foreignkey')
    op.drop_column('generated_posts', 'poll_options')
    # ### end Alembic commands ###
