"""add top_topics to channel_dna

Revision ID: 51ee07bccc46
Revises: 4527f99f4366
Create Date: 2026-06-23 14:43:40.797641
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ee07bccc46'
down_revision: Union[str, None] = '4527f99f4366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_dna', sa.Column('top_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_dna', 'top_topics')
    # ### end Alembic commands ###
