"""phase1 all 14 tables

Revision ID: d810ad1f7031
Revises: 0001_initial_empty
Create Date: 2026-06-23 10:32:26.638503
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd810ad1f7031'
down_revision: Union[str, None] = '0001_initial_empty'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('tier', sa.Enum('new', 'mid', 'established', name='tier'), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('growth_goal', sa.String(length=256), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('onboarding', 'active', 'paused', name='channel_status'), nullable=False),
    sa.Column('needs_strategy_review', sa.Boolean(), nullable=False),
    sa.Column('strategy_review_reason', sa.String(length=256), nullable=True),
    sa.Column('score_threshold', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_telegram_username'), 'channels', ['telegram_username'], unique=True)
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('agent', sa.Enum('channel_dna', 'competitor_intelligence', 'analytics', 'strategy', 'content_intelligence', name='agent_name'), nullable=False),
    sa.Column('trigger', sa.Enum('cron_daily', 'cron_weekly', 'cron_monthly', 'post_slot', 'manual', name='agent_trigger'), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='run_status'), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_dna',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('avg_views_per_post', sa.Float(), nullable=True),
    sa.Column('avg_er', sa.Float(), nullable=True),
    sa.Column('post_frequency_per_day', sa.Float(), nullable=True),
    sa.Column('best_post_hour', sa.SmallInteger(), nullable=True),
    sa.Column('best_post_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_content_formats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tone_fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audience_geo_top3', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('growth_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('insufficient_data', sa.Boolean(), nullable=False),
    sa.Column('analysed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_username', sa.String(length=64), nullable=False),
    sa.Column('competitor_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('post_frequency_per_day', sa.Float(), nullable=True),
    sa.Column('avg_er', sa.Float(), nullable=True),
    sa.Column('top_content_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('telegram_api', 'tgstat', 'telemetr', 'duckduckgo', name='discovery_source'), nullable=True),
    sa.Column('rank', sa.SmallInteger(), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('has_disappearing_messages', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'competitor_username', name='uq_channel_competitor')
    )
    op.create_table('content_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('rss', 'website', 'telegram_channel', 'keyword_db', name='source_type'), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('fetch_interval_mins', sa.Integer(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avg_quality_score', sa.Float(), nullable=False),
    sa.Column('total_items_scored', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_type', sa.Enum('daily', 'weekly', 'monthly', name='strategy_type'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('post_frequency_per_day', sa.Float(), nullable=True),
    sa.Column('content_mix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('growth_tactics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', name='strategy_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('text_preview', sa.Text(), nullable=True),
    sa.Column('format', sa.Enum('text', 'photo', 'video', 'poll', 'link', name='competitor_post_format'), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('forwards', sa.Integer(), nullable=True),
    sa.Column('reactions_count', sa.Integer(), nullable=True),
    sa.Column('er', sa.Float(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('format_tag', sa.String(length=32), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('raw', 'scored', 'used', 'dropped', name='content_item_status'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_external_url'), 'content_items', ['external_url'], unique=False)
    op.create_table('cron_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.Enum('channel_dna', 'competitor_intelligence', 'analytics', 'strategy', 'content_intelligence', name='agent_name'), nullable=False),
    sa.Column('cron_expression', sa.String(length=32), nullable=True),
    sa.Column('cadence_label', sa.Enum('daily', 'weekly', 'monthly', 'post_slot', 'custom', name='cadence_label'), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('relevance', sa.SmallInteger(), nullable=True),
    sa.Column('freshness', sa.SmallInteger(), nullable=True),
    sa.Column('novelty', sa.SmallInteger(), nullable=True),
    sa.Column('goal_alignment', sa.SmallInteger(), nullable=True),
    sa.Column('virality', sa.SmallInteger(), nullable=True),
    sa.Column('competitor_set', sa.SmallInteger(), nullable=True),
    sa.Column('brand_safety', sa.SmallInteger(), nullable=True),
    sa.Column('total_score', sa.SmallInteger(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('threshold_used', sa.SmallInteger(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id')
    )
    op.create_table('generated_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_task_id', sa.Uuid(), nullable=True),
    sa.Column('post_text', sa.Text(), nullable=True),
    sa.Column('post_format', sa.Enum('text', 'photo', 'video', 'poll', 'link', name='generated_post_format'), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(length=256), nullable=True),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'edited', 'rejected', name='review_status'), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_task_id'], ['strategy_tasks.id'], name='fk_generated_posts_strategy_task', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_type', sa.Enum('daily', 'weekly', 'monthly', name='snapshot_type'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('subscriber_delta', sa.Integer(), nullable=True),
    sa.Column('subscriber_delta_pct', sa.Float(), nullable=True),
    sa.Column('avg_views', sa.Float(), nullable=True),
    sa.Column('avg_er', sa.Float(), nullable=True),
    sa.Column('total_posts', sa.SmallInteger(), nullable=True),
    sa.Column('top_post_id', sa.Uuid(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('churn_signal', sa.Boolean(), nullable=False),
    sa.Column('churn_rate', sa.Float(), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['top_post_id'], ['generated_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('format', sa.Enum('text', 'photo', 'video', 'poll', 'link', 'carousel', name='strategy_task_format'), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('generated_post_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'content_sourced', 'generated', 'approved', 'published', 'rejected', name='strategy_task_status'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_post_id'], ['generated_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('generated_post_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_task_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', 'skipped', name='queue_status'), nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_post_id'], ['generated_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_task_id'], ['strategy_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_queue')
    op.drop_table('strategy_tasks')
    op.drop_table('analytics_snapshots')
    op.drop_table('generated_posts')
    op.drop_table('content_scores')
    op.drop_table('cron_jobs')
    op.drop_index(op.f('ix_content_items_external_url'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_table('competitor_posts')
    op.drop_table('strategies')
    op.drop_table('content_sources')
    op.drop_table('competitors')
    op.drop_table('channel_dna')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_channels_telegram_username'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
